services:

  postgresql:
    image: postgres:16
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: military_front
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      DATABASE_URL: postgresql://asa:asa@postgresql:5432/asa?schema=public
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: secret
      MONGODB_URL: mongodb://mongo
      NODE_ENV: production
      TZ: UTC
      SMTP_SERVER_USERNAME: mustakaev.dmitry@yandex.ru
      SMTP_SERVER_PASSWORD: xyakitqdkejfjtlb
      SMTP_SERVER_HOST: smtp.yandex.com
      SMTP_SERVER_PORT: 465
      SMTP_SERVER_SECURE: "true"
      SITE_MAIL_SENDER: mustakaev.dmitry@yandex.ru
    entrypoint: ["/bin/sh", "-c" , "npx prisma migrate deploy && node server.js"]

    depends_on:
      postgresql:
        condition: service_healthy